site_name: Docs
site_url: https://docs.cloudnativerioja.com/
site_description: Proyecto de documentación de Cloud Native Rioja
repo_name: cloudnativerioja/docs-k8s

repo_url: https://github.com/cloudnativerioja/docs-k8s
nav:
  - Inicio: "index.md"
  - Tutoriales:
      - "tutoriales/Inicio.md"
      - "tutoriales/Creación_de_un_cluster_de_Kubernetes_con_CIVO_y_Terraform.md"
      - "tutoriales/Encriptar_y_desencriptar_secrets_con_Sealed_Secrets.md"
  - Charlas:
      - "charlas/Inicio.md"
  - Recursos:
      - "recursos/Recursos.md"
plugins:
  - search:
      lang: es
theme:
  name: material
  logo: assets/logo-cncf-rioja.svg
  favicon: assets/Kubernetes_logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom
      accent: custom

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: custom
      accent: custom
  font:
    text: Roboto
  features:
    - navigation.tabs
    - header.autohide
    - navigation.footer
  icon:
    repo: fontawesome/brands/github
  language: es
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cloudnativerioja
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cloud-native-rioja
markdown_extensions:
  - attr_list

copyright: Copyright &copy; 2023 Cloud Native Rioja
